config/routes.rb
Rails.application.routes.draw do
  resources :meetings
  devise_for :users
  root to: "pages#home"

  get 'dashboard', to: 'pages#dashboard'
  get "courses/category", to: "courses#category"
  get "courses/:category/index", to: "courses#index", as: :courses_category_index
  get "/mycalendar", to: "calendar#mycalendar", as: :my_calendar
  get "myprofile", to: "pages#profile"

  resources :courses, except: [:index] do
    get 'calendar', to: 'calendar#index', as: :calendar
    resources :orders, only: [:show, :create] do
      resources :payments, only: :new
    end
    resources :sessions
    resources :reviews, only: [:index, :show, :new, :create, :destroy]
    resources :bookings, except: [:destroy]
    resources :chatrooms, only: [:new, :create] do
    end
  end

  mount StripeEvent::Engine, at: '/stripe-webhooks'

  scope :users do
    get 'sessions/:id/details', to: 'sessions#details', as: :details_session
  end

  # delete 'bookings/:id', to: 'bookings#destroy', as: 'cancel_booking'
  resources :bookings, only: [:destroy]

  # Adding the calendar route without changing the root
  resources :chatrooms, only: [:show] do
    resources :messages, only: [:create]
  end
end

app/views/shared/_course_info.html.erb
<div class="container">
  <p>Course name: <%= @course.title %></p>
  <p>Price: <%= @course.price %></p>
  <p>Teacher: <%= @course %></p>
  <p>Course description: <%= @course.description %></p>
  <p>Category: <%= @course.category %></p>
  <p>Size: <%= @course.size %></p>
  <p>Session's details:
    <% @course.sessions.each do |session| %>
      <div>
        <p>Session start_time: <%= session.start_time %></p>
        <p>Session end_time: <%= session.end_time %></p>
      </div>
    <% end %>
  </p>

  </div>

app/views/shared/_course_of_the_year_carousel.html.erb
<div class="responsive-cards-home-page">
    <div class="card-container">
      <% @courses_of_the_year.each do |course| %>
        <div class="card">
          <%= link_to course_path(course), class: "card-link" do %>
            <% if course.photo.attached? %>
              <%= cl_image_tag course.photo.key, class: "card-img-top" %>
            <% else %>
              <%= image_tag course.image_url, class: "card-img-top", alt: course.title %>
            <% end %>
            <div class="card-body">
              <p class="card-title"><%= course.title %></p>
            </div>
            <% end %>
            <% if course.end_date <= Date.today %>
              <%= link_to 'Add a Review', new_course_review_path(course), class: 'btn btn-primary' %>
            <% end %>
            <li class="course-item mt-3">
              <div class="course-header">
                <div class="rating-stars">
                  <% rating = course.average_rating || 0 %>
                  <% full_stars = rating.to_i %>
                  <% has_half_star = (rating - full_stars) >= 0.5 %>
                  <% full_stars.times do %>
                    <i class="fa-solid fa-star filled"></i>
                  <% end %>
                  <% if has_half_star %>
                    <i class="fa-solid fa-star-half-stroke filled"></i>
                  <% end %>
                  <% (5 - full_stars - (has_half_star ? 1 : 0)).times do %>
                    <i class="fa-solid fa-star empty"></i>
                  <% end %>
                </div>
              </div>
              <p class="rating-text"><% rating == 0 ? 'No ratings yet' : rating %></p>
            </li>
        </div>
      <% end %>
    </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_home_banner_carousel.html.erb
<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">

    <div class="carousel-item active p-0">
      <div class="carousel-background carousel-background-second p-0">
        <div class="card-on-carousel">
          <h2 class="gupter-bold px-0">Skills that drive you forward</h2>
          <p>Unlock the skills you need to not only achieve your goals but to thrive in a competitive landscape. Transform your future with us and become a leader in your field!</p>
          <button class="carousel-button btn btn-primary">Get Your Own Learning Plans</button>
        </div>
      </div>
    </div>

    <div class="carousel-item active p-0">
      <div class="carousel-background carousel-background-first p-0">
        <div class="card-on-carousel">
          <h2 class="gupter-bold px-0">Learning that gets you</h2>
          <p>Skills for your present (and your future). Get started with us.</p>
        </div>
      </div>
    </div>

  </div>

  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/shared/_map.html.erb
<% if @course.location %>
<div style="width: 100%; height: 350px;"
  data-controller="map"
  data-map-marker-value="<%= @marker.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
<% end %>

app/views/shared/_marker.html.erb
<%= image_tag "icon1.png", height: 55, width: 55 %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand mt-2" do %>
      <%= image_tag "logo_green.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon" id="navbarToggler"></span>
    </button>
    <div class="collapse navbar-collapse mt-3" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Become a teacher", new_course_path, class: "become-teacher"%>
          </li>
          <li class="nav-itme">
            <%= link_to 'My Calendar', my_calendar_path, class: 'become-teacher' %>
          </li>

          <li class="nav-item dropdown ms-3">
            <div class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="background-color:white">
              <% if current_user.photo.attached? %>
                <%= cl_image_tag current_user.photo.key, class: "avatar", alt: "Go to dashboard" %>
              <% elsif current_user.image_url.present? %>
                <%= image_tag current_user.image_url, class: "avatar", alt: "Go to dashboard" %>
              <% else %>
                <div class="name-card">
                  <%= current_user.first_name[0] + current_user.last_name[0] %>
                </div>
              <% end %>
            </div>
            <div class="dropdown-menu dropdown-menu-end w-20" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="/dashboard">My Page</a>
              <a class="dropdown-item" href="/myprofile">My profile</a>
              <a class="dropdown-item" data-turbo-method="delete" href="/users/sign_out">Log out</a>
            </div>
          </li>

            <%# <%a href="/dashboard" class="avatar text-decoration-none"> %>
              <%# <% if current_user.photo.attached? %>
                <%# <%= cl_image_tag current_user.photo.key, class: "avatar", alt: "Go to dashboard" %>
              <%# <% elsif current_user.image_url.present? %>
                <%# <%= image_tag current_user.image_url, class: "avatar", alt: "Go to dashboard" %>
              <%# <% else %>
                <%# <div class="name-card"> %>
                  <%# <%= current_user.first_name[0] + current_user.last_name[0] %>

              <%# <% end %>
            <%# </a> %>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link login" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>
<div class="category-bar">
  <ul class="category-list">
    <li class="category-item">
      <%= link_to "Technology", courses_category_index_path("technology"), class: "category-link" %>
    </li>
    <li class="category-item"><%= link_to "Education", courses_category_index_path("education"), class: "category-link" %></li>
    <li class="category-item"><%= link_to "Cooking", courses_category_index_path("cooking"), class: "category-link" %></li>
    <li class="category-item"><%= link_to "Gardening", courses_category_index_path("gardening"), class: "category-link" %></li>
    <li class="category-item"><%= link_to "Sports", courses_category_index_path("sports"), class: "category-link" %></li>
    <li class="category-item"><%= link_to "Others", courses_category_index_path("others"), class: "category-link" %></li>
  </ul>
</div>
<script>
  const toggler = document.getElementById("navbarSupportedContent");
  toggler.addEventListener("hide.bs.collapse", (event) => {
    event.stopImmediatePropagation();
    console.log("test")
  })
  toggler.addEventListener("show.bs.collapse", (event) => {
    event.stopImmediatePropagation();
    console.log("test")
  })
</script>

app/views/shared/_popup.html.erb
<h5 class="merriweather-light course-title-in-popup"><%= @course.title %></h5>
<p class="course-location-in-popup"><i class="fa-solid fa-map-pin pin"></i><%= @course.location %></p>

app/views/shared/_session_form.html.erb
<div class="container">
  <h2 class="login-heading">New Class</h2>
  <%= simple_form_for([@course, @session], html: { class: "login-form custom-form-width text-start" }) do |f| %>
  <div class="form-inputs">
    <%= f.input :title, input_html: { class: "form-control" } %>
    <%= f.input :description, input_html: { class: "form-control" } %>
    <%= f.input :date, input_html: { class: "form-control" } %>
    <%= f.input :start_time, input_html: { class: "form-control" } %>
    <%= f.input :end_time, input_html: { class: "form-control" } %>
    <div class="form-actions">
      <%= f.submit "Submit", class: "btn btn-primary btn-block" %>
    </div>
  <% end %>
  </div>
</div>