config/routes.rb
Rails.application.routes.draw do
  resources :meetings
  devise_for :users
  root to: "pages#home"

  get 'dashboard', to: 'pages#dashboard'
  get "courses/category", to: "courses#category"
  get "courses/:category/index", to: "courses#index", as: :courses_category_index
  get "/mycalendar", to: "calendar#mycalendar", as: :my_calendar
  get "myprofile", to: "pages#profile"

  resources :courses, except: [:index] do
    get 'calendar', to: 'calendar#index', as: :calendar
    resources :orders, only: [:show, :create] do
      resources :payments, only: :new
    end
    resources :sessions
    resources :reviews, only: [:index, :show, :new, :create, :destroy]
    resources :bookings, except: [:destroy]
    resources :chatrooms, only: [:new, :create] do
    end
  end

  mount StripeEvent::Engine, at: '/stripe-webhooks'

  scope :users do
    get 'sessions/:id/details', to: 'sessions#details', as: :details_session
  end

  # delete 'bookings/:id', to: 'bookings#destroy', as: 'cancel_booking'
  resources :bookings, only: [:destroy]

  # Adding the calendar route without changing the root
  resources :chatrooms, only: [:show] do
    resources :messages, only: [:create]
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :set_course, only: %i[show edit update destroy]

  def category
  end

  def index
    if params[:query].present?
      @courses = Course.where(category: params[:category]).search_by_title_and_location(params[:query])
    else
      @courses = Course.where(category: params[:category])
    end
  end

  def show
    @user = @course.user
    @marker = {
      lat: @course.latitude,
      lng: @course.longitude,
      info_window: render_to_string(partial: "shared/popup", locals: { course: @course }),
      marker_html: render_to_string(partial: "shared/marker")
    }
    @booking = Booking.new
  end

  def new
    # @course = Course.new
    # @course.user = current_user
    # @course.build_user unless @course.user
    @course = Course.new(user: current_user)
  end

  def create
    @course = Course.new(course_params)
    @course.user = current_user

    # if @course.location.present?
    #   @course.geocode # Force geocoding
    #   if @course.latitude.nil? || @course.longitude.nil?
    #     flash.now[:alert] = "Unable to geocode the provided address. Please check and try again."
    #     render :new and return
    #   end

    # else
    #   flash.now[:alert] = "Address is required for course location."
    #   render :new and return
    # end

    # if @course.save
    #   @marker = {
    #     lat: @course.latitude,
    #     lng: @course.longitude,
    #     info_window: render_to_string(partial: "shared/popup", locals: { course: @course }),
    #     marker_html: render_to_string(partial: "shared/marker")
    #   }
    #   update_learning_topics
    #   # update_self_introduction
    #   redirect_to course_path(@course), notice: 'Course was successfully created.'
    # else
    #   render :new
    # end


    if @course.format == "in-person" && @course.location.blank?
      flash.now[:alert] = "Address is required for in-person courses."
      render :new and return
    end

    if @course.location.present?
      @course.geocode # Force geocoding
      if @course.latitude.nil? || @course.longitude.nil?
        flash.now[:alert] = "Unable to geocode the provided address. Please check and try again."
        render :new and return
      end
    end

    if @course.save
      update_learning_topics
      redirect_to course_path(@course), notice: 'Course was successfully created.'
    else
      render :new
    end

  end

  def edit
    @course = Course.includes(:user).find(params[:id])
  end

  def update
    if @course.update(course_params)
      update_learning_topics
      redirect_to course_path(@course), notice: 'Course was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @course.destroy
    redirect_to dashboard_path, status: :see_other
  end

  private

  def update_learning_topics
    if params[:learning_topic] && params[:learning_topic][:content]
      @learning_topics_content = params[:learning_topic][:content]
      @course.learning_topics.destroy_all
      @learning_topics_content.each do |content|
        LearningTopic.find_or_create_by(content: content, course: @course)
      end
    end
  end

  # def update_self_introduction
  #   if params[:course][:user_attributes][:self_introduction]
  #     @course.user.update(self_introduction: params[:course][:user_attributes][:self_introduction])
  #   end
  # end

  def set_course
    @course = Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:price, :title, :description, :category, :size, :capacity, :location, :format, :start_date, :end_date, :image_url, :photo, learning_topics_content:[])
  end
end

app/views/courses/edit.html.erb
<div data-controller="course-format capacity dynamic-fields" class="container">
  <h2 class="login-heading">Edit Your Course</h2>

  <%= simple_form_for(@course, html: { class: "login-form custom-form-width text-start", multipart: true }) do |f| %>
    <div class="form-inputs">
      <%= f.input :title, input_html: { class: "form-control" }, placeholder: "e.g. Learn Photoshop CS6 from Scratch" %>
      <%= f.input :description, input_html: { class: "form-control large-text-field" }, placeholder: "e.g.Learn to make innovative web apps with Ruby on Rails and unleash your creativity" %>

      <div data-controller="datepicker">
        <%= f.input :start_date,
                    as: :string,
                    input_html: { data: { datepicker_target: "startDate"},
                    class: "form-control",
                    placeholder: "Select a start date"
                    }%>
        <%= f.input :end_date,
                    as: :string,
                    input_html: { data: { datepicker_target: "endDate"},
                    class: "form-control",
                    placeholder: "Select an end date"
                    } %>
      </div>

      <%= f.input :size, collection: %w[group private], input_html: {
        class: "form-control",
        data: {
          capacity_target: "size",
          action: "change->capacity#toggleCapacityField"
        }},
        prompt: "Is it a group class or private class?"
       %>

      <div class="d-none" data-capacity-target="capacity">
        <%= f.input :capacity, input_html: { class: "form-control" } %>
      </div>

      <%= label_tag "Learning topics", "Learning topics*", class: "form-label" %>
        <div id="leaning-topics-container" data-dynamic-fields-target="container">
        <% @course.learning_topics.each do |topic| %>
          <%= text_field_tag "learning_topic[content][]", topic.content, class: "form-control" %>
        <% end %>
      </div>
      <button type="button" id="add-learning-topic" class="btn btn-primary mb-2" data-action="click->dynamic-fields#addField">+ Add more topics</button>

      <%= f.input :category, collection: %w[technology education cooking gardening sports others], input_html: { class: "form-control" }, prompt: "Choose a category" %>

      <%= f.input :price, input_html: { class: "form-control" } %>

      <%= f.input :format, collection: %w[online in-person],
        input_html: {
          class: "form-control",
          data: {
            course_format_target: "format",
            action: "change->course-format#togglelocationField"
          }
        }, prompt: "Is it an online course or a In-person course?" %>

      <div class="d-none" data-course-format-target="location">
        <%= f.input :location,
                    input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
                    wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
        %>
      </div>

      <%#= f.input :photo, input_html: { class: "form-control" }, label: "Course Photo" %>
      <%#= f.hidden_field :photo, value: @course.image_url %>
      <div class="form-group">
  <%= f.label :photo, "Course Photo" %>



  <%= f.input :photo,
              as: :file,
              input_html: { class: "form-control-file" },
              label: false %>
</div>

      <%= f.fields_for :user do |user_field| %>
        <%= user_field.input :self_introduction, input_html: { class: "form-control large-text-field" } %>
      <% end %>
    </div>

    <div class="form-actions">
      <%= f.submit "Submit", class: "btn btn-primary btn-block" %>
    </div>
  <% end %>
</div>

app/views/courses/index.html.erb
<div class="image-container">
  <%= image_tag image_path("#{params[:category]}.jpeg"), class: "image-course-index" %>
  <div class="image-overlay">
    <%= params[:category].capitalize %>
  </div>
</div>

<div class="container my-3">
  <div class="row justify-content-center">
    <div class="col-sm-6 my-3">
      <%= form_with url: courses_category_index_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: " 🔍 Search for course name or location"
        %>
        <%= submit_tag "Search", name: "", class: "d-none" %>
      <% end %>
    </div>
  </div>
  <% if @courses.any? %>
    <% @courses.each do |course| %>
      <% if course.end_date >= Date.today %>
        <div class="d-flex mb-3 border rounded-end rounded-start p-3 course-card">
          <div class="course-image me-3">
            <% if course.photo.attached? %>
              <%= cl_image_tag course.photo.key, class: "image-foreach-course" %>
            <% elsif course.image_url.present? %>
              <%= image_tag course.image_url, alt: course.title, class: "image-foreach-course" %>
            <% end %>
          </div>
          <div class="d-flex justify-content-between flex-grow w-100 course-description-index-course">
            <div class="course-description">
              <%= truncate(course.title, length: 45, separator: ' ') %> <br>
              Description:
              <%= truncate(course.description, length: 32, separator: ' ') %> <br>
              Price: $ <%= course.price %>
            </div>
            <div class="type-of-course">
              Type: <%= course.size.capitalize %> Class
            </div>
            <div class="hover-black">
              <%= link_to "More details", course_path(course), class: "more-details-button text-decoration-none fw-normal"%>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  <% else %>
    <div class="text-center my-5">
      Sorry, no courses found.
    </div>
  <% end %>
</div>

app/views/courses/new.html.erb
<div data-controller="course-format capacity dynamic-fields" class="container">
  <h2 class="login-heading">Course Registration</h2>

  <%= simple_form_for(@course, html: { class: "login-form custom-form-width text-start", multipart: true }) do |f| %>
    <div class="form-inputs">
      <%= f.input :title, input_html: { class: "form-control" } %>
      <%= f.input :description, input_html: { class: "form-control large-text-field" } %>

      <div data-controller="datepicker">
        <%= f.input :start_date,
                    as: :string,
                    input_html: { data: { datepicker_target: "startDate"},
                    class: "form-control",
                    placeholder: "Start date"
                    }%>
        <%= f.input :end_date,
                    as: :string,
                    input_html: { data: { datepicker_target: "endDate"},
                    class: "form-control",
                    placeholder: "End date"
                    } %>
      </div>

      <%= f.input :size, collection: %w[group private], input_html: {
        class: "form-control",
        data: {
          capacity_target: "size",
          action: "change->capacity#toggleCapacityField"
        }},
        prompt: "Is it a group class or private class?"
       %>

      <div class="d-none" data-capacity-target="capacity">
        <%= f.input :capacity, input_html: { class: "form-control" } %>
      </div>

      <div data-dynamic-fields-target="container">
        <%= label_tag "Learning topics", "Learning topics*", class: "form-label" %>
        <%= text_field_tag "learning_topic[content][]", nil, class:"form-control", placeholder: "E.g.: Define the roles and responsibilities of a project manager" %>
        <%= text_field_tag "learning_topic[content][]", nil, class:"form-control", placeholder: "E.g.: Estimate project timelines and budgets" %>
        <%= text_field_tag "learning_topic[content][]", nil, class:"form-control", placeholder: "E.g.: Identify and manage project risks" %>
        <%= text_field_tag "learning_topic[content][]", nil, class:"form-control", placeholder: "E.g.: Complete a case study to manage a project from conception to completion" %>
      </div>
      <button type="button" id="add-learning-topic" class="btn btn-primary mb-2" data-action="click->dynamic-fields#addField">+ Add more topics</button>

      <%= f.input :category, collection: %w[technology education cooking gardening sports others], input_html: { class: "form-control" }, prompt: "Choose a category" %>

      <%= f.input :price, input_html: { class: "form-control" } %>

      <%= f.input :format, collection: %w[online in-person],
        input_html: {
          class: "form-control",
          data: {
            course_format_target: "format",
            action: "change->course-format#togglelocationField"
          }
        }, prompt: "Online or in-person?" %>

      <div data-course-format-target="location">
        <%= f.input :location,
                    input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
                    wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
        %>
      </div>

      <%= f.input :photo, as: :file, input_html: { class: "form-control" }, label: "Course Photo" %>
    </div>

    <div class="form-actions">
      <%= f.submit "Submit", class: "btn btn-primary btn-block" %>
    </div>
  <% end %>
</div>

app/views/courses/show.html.erb
<div class="row">
  <div class="col-12">
    <div class="banner">
      <div class="box_container py-5">
        <div id="banner_content">
          <h2 class="archivo-black-regular"><%= @course.title %></h2>
          <div class="banner-discription">
            <p class="merriweather-light">Course description: <%= @course.description %></p>
            <p class="merriweather-light">Class size: <%= @course.size == "group" ? " #{@course.capacity} people" : "#{ @course.size }"%></p>
            <p class="merriweather-light">Created by <%= @course.user.username %></p>
            <% if @course.reviews.present? %>
              <p class="merriweather-light">Rating:
                <% sum_rating = @course.reviews.sum(:rating)%>
                <% total_reviews = @course.reviews.size %>
                <% if total_reviews > 0 %>
                  <% average_rating = sum_rating.to_f / total_reviews %>
                <% else %>
                  <% average_rating = 0 %>
                <% end %>
                <% average_rating = average_rating.round(1) %>
                <%= average_rating %>
                <% full_stars = average_rating.to_i %>
                <% has_half_star = (average_rating - full_stars) >=0.5 %>

                <% full_stars.times do %>
                  <i class="fa-solid fa-star"></i>
                <% end %>

                <% if has_half_star %>
                  <i class="fa-solid fa-star-half-stroke filled"></i>
                <% end %>
              <% end %>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="d-flex">
  <div class="row">

    <div class="col-12 col-lg-8">
      <div class="box_container">

        <!-- what you will learn box -->
        <div class="what_you_will_learn">
          <h4 class="archivo-black-thin">What you'll learn</h4>
          <ul>
            <% @course.learning_topics.each do |topic| %>
            <li><%= topic.content %></li>
            <% end %>
          </ul>
        </div>

        <div class="d-flex justify-content-between see-all-the-classes-for-this-course ">
          <div>
              <%= link_to "View all sessions in calendar", course_calendar_path(@course), class: "calendarlink" %>
          </div>
        </div>

        <!-- teacher information card -->
        <div class="teacher-info-card">
          <h3 class="kanit-regular">Instructor</h3>
          <p><%= @course.user.first_name %> <%= @course.user.last_name %></p>
          <div class="d-flex my-2 align-items-center">
            <% if @course.user.image_url? %>
              <%= image_tag @course.user.image_url, class: "teacher-photo" %>
            <% elsif @course.user.photo.present? %>
              <%= cl_image_tag @course.user.photo.key, class: "teacher-photo" %>
            <% else %>
              <div class="avatar-lg"><h3><%= @course.user.first_name.first.upcase %><%= @course.user.last_name.first.upcase %></h3></div>
            <% end %>
            <div class="teacher-block-list-item-content">
              <div class="d-flex">
                <i class="fa-solid fa-star me-3"></i>
                <p><%= average_rating %> Instructor Rating</p>
              </div>
              <div class="d-flex">
                <i class="fa-solid fa-certificate me-3"></i>
                <p><%= @course.reviews.size %> Reviews</p>
              </div>
              <div class="d-flex">
                <i class="fa-solid fa-user-graduate me-3"></i>
                  <% course_booking_num = @course.bookings.size %>
                  <% course_num = @user.courses.size %>
                  <% students_num = course_booking_num * course_num %>
                <p><%= students_num %> Students</p>
              </div>
              <div class="d-flex">
                <i class="fa-solid fa-circle-play me-3"></i>
                <p><%= course_num %> Courses</p>
              </div>
            </div>
          </div>
          <%= @course.user.self_introduction %>
          <div class="text-end">
            <% if @course.user == current_user %>
              <%= link_to edit_user_registration_path(current_user) do %>
                <%= content_tag(:i, "", class: "fa-solid fa-pen-to-square") %>
              <% end %>
            <% end %>
          </div>
        </div>

        <!-- review card -->
        <div class="review-card">
          <% if @course.reviews.present? %>
            <div id="rating"><i class="fa-solid fa-star"></i> <%= average_rating %> course rating</div>
          <% end %>
            <% @course.reviews.each do |review| %>
            <div class="each-review-card">
              <div class="d-flex align-items-baseline">
                <div class="avatar"><%= review.user.first_name.first.upcase %><%= review.user.last_name.first.upcase %></div>
                <div id="name">
                  <%= review.user.first_name %> <%= review.user.last_name.first.upcase %>.
                </div>
                <p>
                  <% review.rating.times do %>
                    <i class="fa-solid fa-star"></i>
                  <% end %>
                </p>
              </div>
              <p><%= review.content %></p>
            </div>
            <% end %>
        </div>

        <!-- map -->
        <% if @course.location.present? %>
          <div id="map">
            <h3 class="kanit-regular">Location</h3>
            <p><%= @course.location %></p>
            <%= render "shared/map" %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="col-12 col-lg-4 booking-card-container">
    <!-- course booking card -->
      <div class="course_booking_card">
          <% if @course.image_url? %>
            <img src="<%= @course.image_url%>" alt="" class="course_image">
          <% elsif @course.photo.attached? %>
             <%= cl_image_tag @course.photo.key, class: "course_image" %>
          <% end %>
          <div class="course_booking_card_content_price">
            <h4 class="merriweather-black-italic mt-3">A$ <%= @course.price %></h4>
          <!-- Button trigger modal -->
<div class="my-3">
  <% if @course.user == current_user %>
    <%= link_to "Edit Course", edit_course_path(@course), class: "edit-course-button", style: "text-decoration: none;" %>
    <%= link_to "Delete Course",
        course_path(@course),
        data: {
          turbo_method: :delete,
          turbo_confirm: "Are you sure you want to delete the course '#{@course.title}' permanently? This action cannot be undone."
        },
        class: "edit-course-button",
        style: "text-decoration: none;"
    %>
    <% if @course.chatroom %>
      <div class="view-chatroom">
        <%= link_to "Enter Chatroom", chatroom_path(@course.chatroom) %>
      </div>
    <% else %>
      <div class="view-chatroom">
        <%= link_to "Create Chatroom", new_course_chatroom_path(@course) %>
      </div>
    <% end %>

  <% else %>
    <% if @course.bookings.exists?(user: current_user) %>
      <button type="button" class="booking_button btn" disabled>
        You have enrolled in this course
      </button>
        <% if @course.chatroom %>
          <div class="view-chatroom">
          <%= button_to "Enter Chatroom", chatroom_path(@course.chatroom), method: :get, class:"edit-course-button", style:"border-radius:10px" %>
          </div>
        <% end %>
        <div class="cancel-booking">
          <% if @course.start_date > 24.hours.from_now %>
            <%= link_to "Cancel booking", booking_path(@course.bookings.find_by(user: current_user)),
                data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this booking?" },
                class: "cancel-link" %>
          <% else %>
            <%= link_to "Cancel booking", "#",
                data: {
                  controller: "booking",
                  action: "click->booking#cancel",
                  booking_warning_value: "Bookings cannot be canceled within 24 hours of the course start time."
                },
                class: "cancel-link warning-link" %>
          <% end %>
        </div>


    <% else %>



      <%= form_tag course_orders_path(@course), id: 'enroll_form' do %>
        <%= hidden_field_tag 'course_id', @course.id %>
        <% if @course.start_date <= Date.today %>
          <%= button_tag disabled: true, type: 'submit', class: 'booking_button' do %>
            Course has started
          <% end %>
        <% elsif (@course.size == "private" && @course.bookings.exists?) ||
                (@course.size == "group" && @course.bookings.size >= @course.capacity) %>
          <%= button_tag disabled: true, type: 'submit', class: 'booking_button' do %>
            This course is full
          <% end %>
        <% else %>
          <%= button_tag type: 'submit', class: 'btn btn-primary' do %>
            Enroll in this course
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</div>




          <!-- Modal -->
          <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel"><%= @course.title %></h5>
                </div>
                <div class="modal-body">
                      <%= render "shared/course_info" %>
                  </div>
                  <div class="modal-footer">
                    <%= simple_form_for([@course, @booking]) do |f| %>
                    <%= f.input :status %>
                    <%= f.submit "Confirm", class:"btn btn-primary"%>
                    <% end %>
                  </div>
                </div>
              </div>
              </div>

          <p id="start_trial">Full Lifetime Access</p>
        </div>

      </div>
    </div>

  </div>
</div>