config/routes.rb
Rails.application.routes.draw do
  resources :meetings
  devise_for :users
  root to: "pages#home"

  get 'dashboard', to: 'pages#dashboard'
  get "courses/category", to: "courses#category"
  get "courses/:category/index", to: "courses#index", as: :courses_category_index
  get "/mycalendar", to: "calendar#mycalendar", as: :my_calendar
  get "myprofile", to: "pages#profile"

  resources :courses, except: [:index] do
    get 'calendar', to: 'calendar#index', as: :calendar
    resources :orders, only: [:show, :create] do
      resources :payments, only: :new
    end
    resources :sessions
    resources :reviews, only: [:index, :show, :new, :create, :destroy]
    resources :bookings, except: [:destroy]
    resources :chatrooms, only: [:new, :create] do
    end
  end

  mount StripeEvent::Engine, at: '/stripe-webhooks'

  scope :users do
    get 'sessions/:id/details', to: 'sessions#details', as: :details_session
  end

  # delete 'bookings/:id', to: 'bookings#destroy', as: 'cancel_booking'
  resources :bookings, only: [:destroy]

  # Adding the calendar route without changing the root
  resources :chatrooms, only: [:show] do
    resources :messages, only: [:create]
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_course
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  def index
    @reviews = @course.reviews
  end

  def show
  end

  def new
    @review = @course.reviews.new
  end

  def create
    @review = @course.reviews.new(review_params)
    if @review.save
      redirect_to course_reviews_path(@course), notice: 'Review was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @review.update(review_params)
      redirect_to course_review_path(@course, @review), notice: 'Review was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @review.destroy
    redirect_to course_reviews_path(@course), notice: 'Review was successfully destroyed.'
  end

  private

  def set_course
    @course = Course.find(params[:course_id])
  end

  def set_review
    @review = @course.reviews.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/views/reviews/_form.html.erb
<%= form_with(model: [review.course, review], local: true) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
        <% review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.select :rating, options_for_select((1..5).map { |i| [i, i] }), {}, { class: 'form-control' } %>
    <!-- Use a dropdown to limit selection to 1-5 -->
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<h1>Reviews</h1>

<%= link_to 'New Review', new_course_review_path(@course), class: 'btn btn-primary' %>

<table class="table table-striped mt-4">
  <thead class="thead-dark">
    <tr>
      <th>Content</th>
      <th>Rating</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.content %></td>
        <td><%= review.rating %></td>
        <td>
          <%= link_to 'Show', course_review_path(@course, review), class: 'btn btn-secondary btn-sm' %>
          <%= link_to 'Edit', edit_course_review_path(@course, review), class: 'btn btn-warning btn-sm' %>
          <%= link_to 'Delete', course_review_path(@course, review), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/reviews/new.html.erb
<!-- app/views/reviews/new.html.erb -->
<h1>New Review</h1>

<%= render 'form', review: @review %>

<% if @review.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

    <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= link_to 'Back', course_reviews_path(@course) %>

app/views/reviews/show.html.erb
<h1>Review</h1>

<p>
  <strong>Content:</strong>
  <%= @review.content %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>

<p>
  <strong>User:</strong>
  <%= @review.user.username %>
</p>

<p>
  <strong>Course:</strong>
  <%= @review.course.title %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>